#!/usr/bin/env sh 
set -e

usage="
Usage: mpost2pdf <input>.mp

converts an mpost file to a pdf file.
"

# Absolute path:
# 
# Usage: abs=`get_abs_path ./deploy/static`
#		 echo $abs
# 
function get_abs_path {
   dir=$(cd `dirname $1` >/dev/null; pwd )
   echo $dir
}
#

# Get basename:
function get_base_name {
	n=$1
	n=$(basename "$n")
	echo "${n%.*}"
}


#if [ $? -eq 0 ]
#then
#    echo "it worked"
#else
#    echo "it failed"
#fi

# Source directory
#
srcdir=`dirname $0`
srcdir=`cd $srcdir; pwd`

#
# Temp directory:
#
# dstdir=`mktemp -d -t bashtmp`
#
# or current:
#
dstdir=`pwd`

function directory_does_exist {
	if [ ! -d "$1" ]; then
		echo 'true'
	else
		echo 'false'
	fi
}

bold=$(tput bold)
reset=$(tput sgr0)
function print {
	printf "${bold}$1${reset}. "
  echo ""
}

function ask_for_key {
	printf "Press [enter] to continue"
	read -s # suppress user input
	echo 
}


# dryrun
dry_run=false
run() {
  echo "$1"
  if [[ $dry_run == false ]] ; then
    eval "$1"
  fi
}

while (($# > 0)) ; do
  option="$1"
  shift

  svg="no"

  case "$option" in

    -h|--help)
      echo "$usage"
      exit
      ;;

    -d|--dry-run)      
      dry_run=true; 
      ;;

    -s|--svg)      
      svg="yes"; 
      ;;
 
    *.mp)
      filename="$option";
      ;;
    *)
       echo "Unknown option $option"
  esac
done

bn=`get_base_name ${filename}`

bntmp="${bn}-tex"
tmp="${bn}-tex.mp"

mpoutput="${bntmp}.1"
tmpoutput="${bntmp}.log"
mpx="${bntmp}.mpx"
pdoutput="${bntmp}.pdf"
sdoutput="${bntmp}.svg"

run "cat $srcdir/src/prologue.mp ${filename} > ${bn}-tex.mp"
print "Processing ${filename}"
run "mpost ${bn}-tex.mp"

print "Converting eps to pdf"
run "epstopdf ${mpoutput}"

print "Cleaning up"
run "rm ${bn}-tex.mp"
run "rm ${mpoutput}"
run "rm ${tmpoutput}"
run "rm ${mpx}"

if [[ "$svg" == "yes" ]]; then
    print "Converting eps to svg"
    run "pdf2svg ${pdoutput} ${sdoutput}"
    run "rm ${pdoutput}"
    run "mv ${sdoutput} ${bn}.svg"
    # Body
    else
      run "mv ${pdoutput} ${bn}.pdf"
fi




